### ISSUE TITLE
Weird NETHER_BRICK and NETHER_BRICK_ITEM items

### ISSUE THREAD

**Issue by Luk-ESC** [NotEnoughUpdates/NotEnoughUpdates-REPO#1025]
There are two items for Nether Bricks which both look like the nether brick block.

They have completely empty recipes, and pressing r on a nether brick (item) that you got by smelting netherrack (the ingot looking one) leads you to a recipe for one of the two.

**Comment by KTrain5169** [comment]
I don't think you can smelt netherrack?

**Comment by KTrain5169** [comment]
@Luk-ESC can you test it now?

**Comment by jani270** [comment]
Fixed in #1147
