### ISSUE TITLE
Missing Hub NPC's

### ISSUE THREAD

**Issue by ItzKatze** [NotEnoughUpdates/NotEnoughUpdates-REPO#1133]
Following Hub NPC's are missing in the REPO:

Billy Joe
Bobby Joe
Curator
Gladiator
Hootie
Hub Selector
Jim Bob
Minikloon
Mort
Salesman
Security Sloth
The Handler

I don't know if they were just forgotten or if this is on purpose how it is, so lmk :).

**Comment by nea89o** [comment]
Probably forgotten / low prio. Pretty sure we originally only did merchants and garden npcs.
