### ISSUE TITLE
[Suggestion] Item Info Attributes

### ISSUE THREAD

**Issue by DarthGigi** [NotEnoughUpdates/NotEnoughUpdates-REPO#1156]
I was wondering if it's possible to add attribute information such as if an item is auctionable, tradable, sellable, etc?

![image](https://github.com/NotEnoughUpdates/NotEnoughUpdates-REPO/assets/47110839/2938e74a-cfbc-43da-845d-fe599568b355)

**Comment by MisterCheezeCake** [comment]
We currently don't have the capacity to display that in the mod. If you think we should, I suggest making a suggestion in the Discord so the team can discuss it more fully. It sounds like a cool idea, but would be work on the mod side and a lot of work on the repo side.

**Comment by jani270** [comment]
This is way too much effort for 0 gain and wont be added to the repo.
