### ISSUE TITLE
HotM Level Requirement for applicable forge recipes

### ISSUE THREAD

**Issue by MattTheCuber** [NotEnoughUpdates/NotEnoughUpdates-REPO#1216]
It would be really cool if you could add the HotM level requirement for all forge recipes that have a requirement (like [this one](https://github.com/NotEnoughUpdates/NotEnoughUpdates-REPO/blob/master/items/REFINED_TUNGSTEN.json#L15-L23)).

This might be kind of weird though as some forge recipes require specific collections levels instead of or in combination with HotM level... Also things like Mole pet require fossils...

**Comment by jani270** [comment]
Sounds like effort...

**Comment by MattTheCuber** [comment]
So true
