### ISSUE TITLE
Slayer requirements are not shown for many crafting recipes

### ISSUE THREAD

**Issue by gerzytet** [NotEnoughUpdates/NotEnoughUpdates-REPO#1336]
I noticed that for many slayer items, the crafting recipe does not show its slayer requirement.
For some of these items, such as REVENANT_SWORD, the slayer_req field is set, but not crafttext.
For others, like REVENANT_LEGGINGS, crafttext is set but not slayer_req.
For others, like WARDEN_HEMET, both are set.

slayer_req present but crafttext empty or missing appears to be the most common case.  It includes the droplet wisp items, tarantula armor, and the voidling minion, to name a few.

I'm willing to go through and standardize it, but which field should be the canonical source of slayer requirement info?  I think a good solution would be slayer_req, in addition to a change to the mod to autogenerate the craft text if slayer_req exists, is valid, and no crafttext is specified.

**Comment by jani270** [comment]
> I noticed that for many slayer items, the crafting recipe does not show its slayer requirement. For some of these items, such as REVENANT_SWORD, the slayer_req field is set, but not crafttext. For others, like REVENANT_LEGGINGS, crafttext is set but not slayer_req. For others, like WARDEN_HEMET, both are set.
> 
> slayer_req present but crafttext empty or missing appears to be the most common case. It includes the droplet wisp items, tarantula armor, and the voidling minion, to name a few.
> 
> I'm willing to go through and standardize it, but which field should be the canonical source of slayer requirement info? I think a good solution would be slayer_req, in addition to a change to the mod to autogenerate the craft text if slayer_req exists, is valid, and no crafttext is specified.

Hey, thanks for the report. Regarding your question about which field should be used: at the moment, only the crafttext field is used in our mod, although slayer_req is being using by third-party sites (e.g., Cofl) for easier parsing. So, for now, both fields should be filled.
