### ISSUE TITLE
[Suggestion] Furnace recipes

### ISSUE THREAD

**Issue by IRISHMAN04** [NotEnoughUpdates/NotEnoughUpdates-REPO#484]
Is there any possibility of furnace recipes being added? I don't know if there are any custom furnace recipes on Hypixel, but Cactus Green not having a crafting recipe of Cactus in furnace, which has a cost of 0.9 makes the [Windows Forms app I'm designing ](https://github.com/IRISHMAN04/HypixelBazaar) kind of break when an Enchanted Cactus costs -25,600 to buy, but sells for 25,028.77.

**Comment by MisterCheezeCake** [comment]
I don't know if we have the functionality to add that.

**Comment by TymanWasTaken** [comment]
This would be more a suggestion for the #neu-suggestions channel in the discord, as it would need to be added to the mod, and then we can add the recipes here

**Comment by SemicolumnDev** [comment]
This is the most comprehensive and public recipe and item list for skyblock Tyman, what else were they gonna use?
I dont see a problem, NEU was supposed to have JEI for skyblock.
If Moul doesn't have a problem with being able to make furnace recipes I wouldn't.

**Comment by IRISHMAN04** [comment]
Thanks, didn't even know there was a neu discord. I'll put it in there as well. Following what Semicolumn says, I was just using this repo as it was extremely easy for Newtonsoft.JSON to parse the recipes for all the skyblock items.

**Comment by IRONM00N** [comment]
You are welcome to make a pr for furnace recipes, it would be far too much effort to add a gui in-game for just a few recipes but if you can find a use you are welcome to add it to the repo.

**Comment by Bowswa** [comment]
I should think you wouldn't need a GUI to show smelting, just a tooltip on the item in the list that says smelted with X or something like that. That way it is still kinda useful in the mod.

**Comment by SemicolumnDev** [comment]
That would still require additional coding by Moul since it wouldn't know how to parse furnace recipes, so you might as well just go all out and make something resembling the JEI recipe viewer
