### ISSUE TITLE
Wooden Pickaxe and some other recipers not here

### ISSUE THREAD

**Issue by CommandCracker8** [NotEnoughUpdates/NotEnoughUpdates-REPO#707]
Hiya

Is there a reason that some items aren't in this list?

**Comment by jani270** [comment]
"some items" is very not helpful, please specify what items you mean.

**Comment by romangraef** [comment]
![image](https://user-images.githubusercontent.com/20768569/161144349-cfd92905-3620-41cf-a412-b7f6a2d46381.png)
people are high, apparently
