### ISSUE TITLE
Gemstone inconsistancies and non existent items?

### ISSUE THREAD

**Issue by Cobble8** [NotEnoughUpdates/NotEnoughUpdates-REPO#746]
![image](https://user-images.githubusercontent.com/41165207/170614333-9efa120f-f1bd-4fb0-beae-670c0619530d.png)
This doesn't exist (even though I know it did at one point, that was over a year ago)
![image](https://user-images.githubusercontent.com/41165207/170614390-31d6c415-3174-41a4-902c-28e47c7a3d69.png)
Tf is this thing?
![image](https://user-images.githubusercontent.com/41165207/170614451-302854cf-ebb5-49eb-920b-3ee662cd70da.png)
The 'Jasper Crystal' should be in the category with the other crystals
The 5 Opal gemstone types should be grouped together like the other gemstones
Although this is kinda neat, why did the pristine enchant come up when I searched 'gemstone'? Nowhere in the lore is the word 'gemstone'

**Comment by jani270** [comment]
1. and 2. are just bugged items they still exist (We have a lot of them in the repo= 
3. and 4. is fixed soon ™️ 
5. You should get glasses

**Comment by jani270** [comment]
Also please just talk in the discord github issues are dumb

**Comment by Cobble8** [comment]
Nopo told me to go here since there isn't a channel for this

**Comment by jani270** [comment]
nopo stop telling these thingy ty
