### ISSUE TITLE
[Missing] SULPHER_SKITTER_DIAMOND

### ISSUE THREAD

**Issue by MattTheCuber** [NotEnoughUpdates/NotEnoughUpdates-REPO#817]
Sorry to be a bother, but we are still missing the item `SULPHER_SKITTER_DIAMOND`.

**Comment by jani270** [comment]
Well i dont have the item so i cant add it

**Comment by MattTheCuber** [comment]
Ok, I will try to find someone

**Comment by jani270** [comment]
> Ok, I will try to find someone

Found someone
